title: Humanities Without Walls PhD Internships Toolkit
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

logo: "/assets/images/hww_logo.png"

url: https://hwwphdinternships.github.io 

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
