title: Humanities Without Walls PhD Internships Toolkit
description: Partnerships between Community Organizations and PhD Students
theme: just-the-docs

color_scheme: hww

logo: "/assets/images/hww_logo.png"

url: https://hwwphdinternships.github.io 

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
